FROM node:20.5.1-bookworm-slim

WORKDIR /usr/src/app

COPY . .

RUN yarn cache clean --force

RUN yarn install --frozen-lockfile --network-timeout 100000

RUN yarn build:development

CMD [ "yarn", "start:development" ]

